# Generated by Django 6.0.2 on 2026-03-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
