# Generated by Django 6.0.2 on 2026-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='codec',
            field=models.CharField(choices=[('av1', 'AV1'), ('h264', 'H264')], max_length=10),
        ),
    ]
